FROM node:22.15.0

WORKDIR /src

COPY ./package.json ./
COPY ./package-lock.json ./ 

RUN npm i

COPY . .

RUN npm run build

RUN npm install -g serve

EXPOSE 3000

CMD ["serve", "-s", "build", "-l", "3000"]