services:
  react-app:
    build:
      context: ./frontend
    image: react-app
    stdin_open: true
    ports:
      - "3000:3000"
    networks:
      - mern-app

  api-server:
    build:
      context: ./backend
    image: api-server
    ports:
      - "5000:5000"
    networks:
      - mern-app
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/mtts

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    networks:
      - mern-app
    volumes:
      - mongo-data:/data/db

networks:
  mern-app:
    driver: bridge

volumes:
  mongo-data:
    driver: local
